# Generated by Django 4.2 on 2026-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='اسم السيارة'),
        ),
    ]
